### PR TITLE
Removed confirmation modal when restoring pages

### PR DESCRIPTION
**Pull request by qgolsteyn**
This PR removes the confirmation modal that appears when trying to restore a page. Instead, the page restored immediately.

**Testing done**

Manual testing

**Issue completed**
https://app.asana.com/0/1121331595459324/1126262288715643

### CODE REVIEW

**Review by houshuang — CHANGES_REQUESTED** [review]
If I delete an individual page with some instances, and when following a link say "create new" instead of "restore", all the old instances are still there. (This doesn't happen with a whole class page).

**Comment by houshuang** [comment]
Also we should switch to the restored page immediately.

**Comment by houshuang** [comment]
@qgolsteyn 	Ping, we should try to get this merged in.

**Comment by qgolsteyn** [comment]
We now go to the page after it is restored.

**Comment by qgolsteyn** [comment]
Regarding the other issue, I opened a new task in Asana:
https://app.asana.com/0/1121331595459324/1127117535559358

**Pull request merged**
