### PR TITLE
Add coordinate dashboard to ac-ranking

### PR DESCRIPTION
**Pull request by lfaucon**

### CODE REVIEW

**Review by houshuang — CHANGES_REQUESTED** [review]
Looks good, but something is broken - if I type in the justification box, it doesn't increase progress, and the submit button stays disabled.

**Review by jkolsen — CHANGES_REQUESTED** [review]
The submit button is broken.

**Comment by lfaucon** [comment]
The bug was due to usage of `Object.keys(activityData.data).length` being used, which I only half removed. This was pretty unsafe given that we don't know what operator will be linked to this activity and we have no control on what this object will be

**Comment by houshuang** [comment]
Looks good to me, Jenny.

**Review by houshuang — DISMISSED** [review]

**Comment by jkolsen** [comment]
Yup, sure. Once Stian's PR has been merged in, we can merge this in.

**Review by jkolsen — APPROVED** [review]

**Pull request merged**
