### PR TITLE
Sidepanel nesting by category

### PR DESCRIPTION
**Pull request by ajainuary**
- [x] Nesting of Activity types by categories. Categories are arranged in an array.
- [x] Fix the width of sidepanel  @ajainuary 
- [x] Issues with selection of activity and clicking the back button @houshuang 
- [ ] Find Icons for the categories (suggestions are welcomed)
- [x] Add search bar
- [x] Show description as a tooltip

Known Issues:
- Library component has its own scrollbar which doesn't scroll. (But the side panel scrollbar scrolls)

### CODE REVIEW

**Comment by houshuang** [comment]
Can you run `npm start eslint`, and fix all the errors?

```js

/Users/stian/src/FROG/frog/imports/client/GraphEditor/SidePanel/ActivityPanel/ChooseActivity.js
    8:8   error  'Divider' is defined but never used. Allowed unused vars must match /_/                no-unused-vars
   10:8   error  'Drawer' is defined but never used. Allowed unused vars must match /_/                 no-unused-vars
   20:8   error  'ListItemIcon' is defined but never used. Allowed unused vars must match /_/           no-unused-vars
   24:8   error  'StarBorder' is defined but never used. Allowed unused vars must match /_/             no-unused-vars
   28:8   error  'ListComponent' is defined but never used. Allowed unused vars must match /_/          no-unused-vars
   29:8   error  'Preview' is defined but never used. Allowed unused vars must match /_/                no-unused-vars
  160:1   error  'ActivityCategory' is a class                                                          no-class-assign
  230:11  error  'closeLibrary' is assigned a value but never used. Allowed unused vars must match /_/  no-unused-vars
  265:34  error  Expected '===' and instead saw '=='                                                    eqeqeq
  269:65  error  Expected '===' and instead saw '=='                                                    eqeqeq
  270:35  error  Expected '===' and instead saw '=='                                                    eqeqeq
  270:47  error  Expected '===' and instead saw '=='                                                    eqeqeq
  275:34  error  Expected '!==' and instead saw '!='                                                    eqeqeq
  276:33  error  Expected '!==' and instead saw '!='                                                    eqeqeq
  295:34  error  Expected '!==' and instead saw '!='                                                    eqeqeq
  296:33  error  Expected '===' and instead saw '=='                                                    eqeqeq
```

**Comment by houshuang** [comment]
Somehow the icon to export to server disappears. Compare develop with your branch;

Screenshot 2019-05-07 at 19 55 33

Screenshot 2019-05-07 at 19 56 02

**Comment by houshuang** [comment]
In the Preview, there's a horizontal scrollbar, and also the scroll of the items cuts off maybe 40 px before the bottom.

Screenshot 2019-05-07 at 19 59 55

Also, if we don't have a scrollbar issue for Library in Preview, why do we have two in Graph Editor, should be possible to fix?

**Comment by houshuang** [comment]
If we're too zoomed in on graph editor, the two buttons have fixed location, and the panel doesn't go the length of the screen.

On the other hand, this is apparently an issue with the old code too. So maybe not worth fixing. Works fine if graph editor is zoomed out.

Screenshot 2019-05-07 at 20 09 18

**Comment by ajainuary** [comment]
Fixed linting and typos that caused glitches in the icon for 'export to server'.

**Comment by houshuang** [comment]
If the sidebar is longer than the graph (which it will always be, scrolling scrolls the whole page)

Screenshot 2019-05-08 at 13 27 23

**Comment by ajainuary** [comment]
Fixed it back (had broken it in the previous commit)

**Pull request merged**
