### PR TITLE
Issue 49

### PR DESCRIPTION
**Pull request by KhalilMrini**

### CODE REVIEW

**Comment by KhalilMrini** [comment]
I don't know why it fails? The project works on my computer

**Comment by houshuang** [comment]
It fails because of a bunch of eslint error. Try running eslint locally.

**Comment by KhalilMrini** [comment]
I cannot fix the last two problems:
   26:20  error  'MSBlobBuilder' is not defined  no-undef
  253:20  error  'FileReader' is not defined     no-undef
Because these types are needed in the code. I saw the eslint documentation but I don't see how to fix it?

**Comment by KhalilMrini** [comment]
I applied an ignore comment on the advice of Louis.

**Pull request merged**
