### PR TITLE
Wiring up ErrorPage if SLUG not found

### PR DESCRIPTION
**Pull request by AbhinavThukral97**
This PR wires up the Error page when accessing undefined sessions using 't/SLUG', with and without login for TeacherView.

### CODE REVIEW

**Comment by lfaucon** [comment]
How does the page actually comes up? When typing the wrong url as a teacher, FROG redirects me towards the previous sections that was opened. Can you tell me steps to reproduce?

**Comment by AbhinavThukral97** [comment]
The error page is rendered if the user account has no sessions to redirect to or an attempt to access the 't/SLUG' is made without login.

**Comment by houshuang** [comment]
Looks good to me. I think we should probably also fail if people try to go to the wrong slug instead of defaulting to a random slug the user has - that was useful before when we were switching users all the time. @lfaucon what do you think?

**Review by houshuang — APPROVED** [review]

**Comment by lfaucon** [comment]
I agree with @houshuang on showing the error page instead of redirecting to an existing previous slug 

I have not been able to replicate triggering the error page. I must be missing something?...

**Comment by AbhinavThukral97** [comment]
I wasn't sure where the redirect functionality was needed. New PR up to fix this.
@lfaucon This can be replicated with any wrong slug now.

**Pull request merged**
