### PR TITLE
bugfix babel crash on syntax error

### LINKED ISSUE #842: watch/watchAll should not crash on syntax error
Before we used to use a node package that just watched for file change, and then ran babel for the entire directory if a file changed. Currently, we are using the --watch function built-in to babel, to automatically rebuild files which are changed. This is more efficient (only one file is rebuilt, when changed).

However, when Babel finds a syntax error (quite often when you are editing), it crashes, and stops rebuilding. We obviously don't want this. 

Someone should look into what's a better way - is it to check if Babel processes die and then restart them? Or use the watch script, but run actions on individual files and not on whole directories?

As an added bonus, it would be great if we could run a single watch script for all of FROG instead of one per directory... I'm wondering if there is a node library which could just watch all of FROG for file changes, and then let us implement the logic (filter out node_modules, only rebuild single files, etc).

### PR DESCRIPTION
**Pull request by prastut**
Fixes #842

### CODE REVIEW

**Review by lfaucon — CHANGES_REQUESTED** [review]
Looks like you changed watchAll, but the problem will still occur with watch. Can you update your PR to fix watch too?

**Comment by prastut** [comment]
@lfaucon good catch, please check now?

**Review by houshuang — DISMISSED** [review]
Awesome!

**Comment by prastut** [comment]
@houshuang this might break if the filename that babel encounters contains src. Fixing this.

**Pull request merged**
