### PR TITLE
UI Fixes with Session (New Tab) View

### PR DESCRIPTION
**Pull request by AbhinavThukral97**

### CODE REVIEW

**Comment by houshuang** [comment]
@lfaucon Seems good me.

**Comment by lfaucon** [comment]
I don't really like the white topbar. It does not stick out from the rest of the page at all. 

@AbhinavThukral97  Can you list all the changes and tell us why you tagged this PR as "in progress" ?

**Comment by houshuang** [comment]
@AbhinavThukral97 ?

**Comment by AbhinavThukral97** [comment]
I'm really sorry I missed this.

I added the white top bar to keep the design uniform with our dashboard view.

The changes here were some UI fixes with design: Spacing fixes of the error messages, changing the top bar design to make it uniform with our general layout. and fixing some linking errors.

**Comment by lfaucon** [comment]
As I said previously, I found the white topbar not great. I replaced it using the color from the theme (see screenshot). I believe this way it keeps the design uniform. @AbhinavThukral97 If you are ok with it, I'll merge it. 

Screenshot from 2019-12-11 13-14-14

**Review by lfaucon — DISMISSED** [review]

**Review by lfaucon — APPROVED** [review]

**Pull request merged**
