### PR TITLE
Upgrading Flow (and everything else)

### PR DESCRIPTION
**Pull request by houshuang**
We're trying to reduce the number of Flow errors, anyone is welcome to help out so we can get on the new version of Flow - we're upgrading from 52 to 64 (https://github.com/facebook/flow/releases?after=v0.57.3)

### CODE REVIEW

**Comment by lfaucon** [comment]
@houshuang After Romain's hard work today I fixed most of the leftover flow errors. The app is not yet working. Can you fix the issue with the connection in `ui/App/index.js`? Also the CI does not install frog correctly anymore.

**Comment by houshuang** [comment]
Great work!

I am still working with the Meteor developers on resolving an issue around conditional imports etc, before this is ready to merge. I will make sure to keep it up to date with develop though.

**Comment by houshuang** [comment]
Turns out there is still an issue with Meteor and decorators, babel etc, which is probably why dynamic import wasn't working as well.

**Comment by lfaucon** [comment]
While testing the graph editor I found this new error:
```
I20180206-14:44:01.550(1)? Exception while invoking method 'sessions.restart' MongoError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}
I20180206-14:44:01.550(1)?     at Function.MongoError.create (/home/louisfaucon/.meteor/packages/npm-mongo/.2.2.34.16ukk9n.tif2++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:31:11)
I20180206-14:44:01.550(1)?     at toError (/home/louisfaucon/.meteor/packages/npm-mongo/.2.2.34.16ukk9n.tif2++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:139:22)
I20180206-14:44:01.551(1)?     at /home/louisfaucon/.meteor/packages/npm-mongo/.2.2.34.16ukk9n.tif2++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/collection.js:1059:67
I20180206-14:44:01.551(1)?     at /home/louisfaucon/.meteor/packages/npm-mongo/.2.2.34.16ukk9n.tif2++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:469:18
I20180206-14:44:01.551(1)?     at _combinedTickCallback (internal/process/next_tick.js:131:7)
I20180206-14:44:01.551(1)?     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by lfaucon** [comment]
Another bug on the graph editor, in `store/uiStore.js`:
```
    reaction(
      () => [this.sidepanelOpen, this.windowWidth],
      () => this.updateGraphWidth()
    );
```
The reaction is never triggered
You can trigger `updateGraphWidth` by exporting as image

**Review by lfaucon — APPROVED** [review]

**Pull request merged**
