### PR TITLE
Feature/toast

### PR DESCRIPTION
**Pull request by qgolsteyn**
This PR adds toasts to FROG, allow to show success/error/misc. events.

**Testing done**

Manual testing. `RestoreDeletedPageModal` in the wiki was update to test this code.

### CODE REVIEW

**Review by RachitMalik12 — CHANGES_REQUESTED** [review]
Please resolve merge conflicts! Thanks :)

**Comment by houshuang** [comment]
@qgolsteyn 	Ping, would be good to get this in?

**Comment by qgolsteyn** [comment]
@RachitMalik12 ready for code review

**Comment by houshuang** [comment]
Trying to open Storybook I get all kinds of errors. This is after pulling the latest update, and doing git clean/initial_setup.

```js
ebpack built 43d3f255548df6e0573c in 6571ms
✖ ｢wdm｣: Hash: 43d3f255548df6e0573c
Version: webpack 4.35.3
Time: 6571ms
Built at: 07/19/2019 11:41:59 AM
                                          Asset      Size        Chunks                    Chunk Names
                                    iframe.html  2.52 KiB                [emitted]
            main.43d3f255548df6e0573c.bundle.js  42.9 KiB          main  [emitted]         main
        main.43d3f255548df6e0573c.bundle.js.map    15 KiB          main  [emitted]         main
    runtime~main.43d3f255548df6e0573c.bundle.js  31.1 KiB  runtime~main  [emitted]         runtime~main
runtime~main.43d3f255548df6e0573c.bundle.js.map  32.3 KiB  runtime~main  [emitted]         runtime~main
    vendors~main.43d3f255548df6e0573c.bundle.js  2.09 MiB  vendors~main  [emitted]  [big]  vendors~main
vendors~main.43d3f255548df6e0573c.bundle.js.map  2.15 MiB  vendors~main  [emitted]         vendors~main
Entrypoint main [big] = runtime~main.43d3f255548df6e0573c.bundle.js runtime~main.43d3f255548df6e0573c.bundle.js.map vendors~main.43d3f255548df6e0573c.bundle.js vendors~main.43d3f255548df6e0573c.bundle.js.map main.43d3f255548df6e0573c.bundle.js main.43d3f255548df6e0573c.bundle.js.map
[0] multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true 64 bytes {main} [built]
[./.storybook/config.js] 311 bytes {main} [built]
[./frog/imports sync recursive \.stories\.jsx?$] ./frog/imports sync \.stories\.jsx?$ 224 bytes {main} [built]
[./node_modules/@storybook/core/dist/server/common/polyfills.js] 120 bytes {vendors~main} [built]
[./node_modules/@storybook/core/dist/server/preview/globals.js] 93 bytes {vendors~main} [built]
[./node_modules/@storybook/core/node_modules/regenerator-runtime/runtime.js] 23 KiB {vendors~main} [built]
[./node_modules/@storybook/react/dist/client/index.js] 1.26 KiB {vendors~main} [built]
[./node_modules/airbnb-js-shims/index.js] 40 bytes {vendors~main} [built]
[./node_modules/core-js/features/symbol/index.js] 251 bytes {vendors~main} [built]
[./node_modules/global/window.js] 232 bytes {vendors~main} [built]
[./node_modules/querystring-es3/index.js] 127 bytes {vendors~main} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {vendors~main} [built]
[./node_modules/webpack-hot-middleware/client-overlay.js] (webpack)-hot-middleware/client-overlay.js 2.17 KiB {vendors~main} [built]
[./node_modules/webpack-hot-middleware/client.js?reload=true] (webpack)-hot-middleware/client.js?reload=true 7.68 KiB {vendors~main} [built]
[./node_modules/webpack-hot-middleware/process-update.js] (webpack)-hot-middleware/process-update.js 4.35 KiB {vendors~main} [built]
    + 554 hidden modules

ERROR in ./frog/imports/ui/Modal/Modal.js
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/stian/src/frog/node_modules/@material-ui/core/esm/Button/index.js` does not match the corresponding path on disk `FROG`.
 @ ./frog/imports/ui/Modal/Modal.js 13:0-46 31:31-37
 @ ./frog/imports/ui/Modal/index.js
 @ ./frog/imports/ui/Modal/Alert.stories.js
 @ ./frog/imports sync \.stories\.jsx?$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./frog/imports/ui/Modal/ModalController.js
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/stian/src/frog/node_modules/@material-ui/core/esm/Dialog/index.js` does not match the corresponding path on disk `FROG`.
 @ ./frog/imports/ui/Modal/ModalController.js 10:0-46 40:43-49
 @ ./frog/imports/ui/Modal/index.js
 @ ./frog/imports/ui/Modal/Alert.stories.js
 @ ./frog/imports sync \.stories\.jsx?$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./frog/imports/ui/Modal/Modal.js
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/stian/src/frog/node_modules/@material-ui/core/esm/DialogActions/index.js` does not match the corresponding path on disk `FROG`.
 @ ./frog/imports/ui/Modal/Modal.js 10:0-60 30:179-192
 @ ./frog/imports/ui/Modal/index.js
 @ ./frog/imports/ui/Modal/Alert.stories.js
 @ ./frog/imports sync \.stories\.jsx?$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./frog/imports/ui/Modal/Modal.js
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/stian/src/frog/node_modules/@material-ui/core/esm/DialogContent/index.js` does not match the corresponding path on disk `FROG`.
 @ ./frog/imports/ui/Modal/Modal.js 11:0-60 30:127-140
 @ ./frog/imports/ui/Modal/index.js
 @ ./frog/imports/ui/Modal/Alert.stories.js
 @ ./frog/imports sync \.stories\.jsx?$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./frog/imports/ui/Modal/Modal.js
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/stian/src/frog/node_modules/@material-ui/core/esm/DialogTitle/index.js` does not match the corresponding path on disk `FROG`.
 @ ./frog/imports/ui/Modal/Modal.js 12:0-56 30:80-91
 @ ./frog/imports/ui/Modal/index.js
 @ ./frog/imports/ui/Modal/Alert.stories.js
 @ ./frog/imports sync \.stories\.jsx?$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./frog/imports/ui/Toast/index.stories.js
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/stian/src/frog/node_modules/@material-ui/core/esm/index.js` does not match the corresponding path on disk `FROG`.
 @ ./frog/imports/ui/Toast/index.stories.js 11:0-43 19:71-77 23:40-46 27:48-54 31:46-52 35:48-54
 @ ./frog/imports sync \.stories\.jsx?$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./frog/imports/ui/Modal/Alert.stories.js
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/stian/src/frog/node_modules/@material-ui/core/esm/index.js` does not match the corresponding path on disk `FROG`.
 @ ./frog/imports/ui/Modal/Alert.stories.js 11:0-43 19:29-35
 @ ./frog/imports sync \.stories\.jsx?$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./frog/imports/ui/Toast/useToast.js
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/stian/src/frog/node_modules/@material-ui/core/esm/index.js` does not match the corresponding path on disk `FROG`.
 @ ./frog/imports/ui/Toast/useToast.js 3:0-55 15:35-41 23:30-40
 @ ./frog/imports/ui/Toast/index.js
 @ ./frog/imports/ui/Toast/index.stories.js
 @ ./frog/imports sync \.stories\.jsx?$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./frog/imports/ui/Modal/Alert.js
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/stian/src/frog/node_modules/@material-ui/core/esm/index.js` does not match the corresponding path on disk `FROG`.
 @ ./frog/imports/ui/Modal/Alert.js 8:0-54 32:25-42
 @ ./frog/imports/ui/Modal/index.js
 @ ./frog/imports/ui/Modal/Alert.stories.js
 @ ./frog/imports sync \.stories\.jsx?$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./frog/imports/ui/Toast/useToast.js
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/stian/src/frog/node_modules/@material-ui/icons/esm/index.js` does not match the corresponding path on disk `FROG`.
 @ ./frog/imports/ui/Toast/useToast.js 4:0-43 28:29-34
 @ ./frog/imports/ui/Toast/index.js
 @ ./frog/imports/ui/Toast/index.stories.js
 @ ./frog/imports sync \.stories\.jsx?$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./frog/imports/ui/Toast/index.stories.js
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/stian/src/frog/node_modules/@storybook/react/dist/client/index.js` does not match the corresponding path on disk `FROG`.
 @ ./frog/imports/ui/Toast/index.stories.js 10:0-45 42:0-9
 @ ./frog/imports sync \.stories\.jsx?$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./frog/imports/ui/Modal/Alert.stories.js
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/stian/src/frog/node_modules/@storybook/react/dist/client/index.js` does not match the corresponding path on disk `FROG`.
 @ ./frog/imports/ui/Modal/Alert.stories.js 10:0-45 26:0-9
 @ ./frog/imports sync \.stories\.jsx?$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./frog/imports/ui/Toast/ToastController.js
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/stian/src/frog/node_modules/notistack/build/index.js` does not match the corresponding path on disk `FROG`.
 @ ./frog/imports/ui/Toast/ToastController.js 2:0-45 8:29-45
 @ ./frog/imports/ui/Toast/index.js
 @ ./frog/imports/ui/Toast/index.stories.js
 @ ./frog/imports sync \.stories\.jsx?$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true

ERROR in ./frog/imports/ui/Toast/useToast.js
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/stian/src/frog/node_modules/notistack/build/index.js` does not match the corresponding path on disk `FROG`.
 @ ./frog/imports/ui/Toast/useToast.js 2:0-40 8:21-32
 @ ./frog/imports/ui/Toast/index.js
 @ ./frog/imports/ui/Toast/index.stories.js
 @ ./frog/imports sync \.stories\.jsx?$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  29.3 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/dist/server/templates/index.ejs] 1.72 KiB {HtmlWebpackPlugin_0} [built]

WARN Broken build, fix the error below.
WARN You may need to refresh the browser.
```

**Comment by houshuang** [comment]
FROG not happy either

```js
W20190719-11:45:28.229(2)? (STDERR) Error: Cannot find module './ToastController'
W20190719-11:45:28.229(2)? (STDERR)     at makeMissingError (packages/modules-runtime.js:222:12)
W20190719-11:45:28.229(2)? (STDERR)     at Module.require (packages/modules-runtime.js:241:17)
W20190719-11:45:28.230(2)? (STDERR)     at Module.moduleLink [as link] (/Users/stian/.meteor/packages/modules/.0.13.0.r5rmc9.d4wpo++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20190719-11:45:28.230(2)? (STDERR)     at index.js (imports/frog-utils/index.js:2:1)
W20190719-11:45:28.230(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190719-11:45:28.230(2)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190719-11:45:28.230(2)? (STDERR)     at Module.moduleLink [as link] (/Users/stian/.meteor/packages/modules/.0.13.0.r5rmc9.d4wpo++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20190719-11:45:28.230(2)? (STDERR)     at api.js (server/api.js:1:1)
W20190719-11:45:28.230(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190719-11:45:28.231(2)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190719-11:45:28.231(2)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20190719-11:45:28.231(2)? (STDERR)     at /Users/stian/src/FROG/frog/.meteor/local/build/programs/server/app/app.js:29219:1
W20190719-11:45:28.231(2)? (STDERR)     at /Users/stian/src/FROG/frog/.meteor/local/build/programs/server/boot.js:419:36
W20190719-11:45:28.231(2)? (STDERR)     at Array.forEach (<anonymous>)
W20190719-11:45:28.231(2)? (STDERR)     at /Users/stian/src/FROG/frog/.meteor/local/build/programs/server/boot.js:228:19
W20190719-11:45:28.231(2)? (STDERR)     at /Users/stian/src/FROG/frog/.meteor/local/build/programs/server/boot.js:479:5
```

**Comment by qgolsteyn** [comment]
Hmm... let me investigate

**Comment by qgolsteyn** [comment]
On my initial attempt, I don't see Storybook crashing after git clean/initial_setup :thinking:

**Comment by houshuang** [comment]
Tried again - same exact thing. For FROG it looks like you might be important ToastController in frog-utils from . even after you moved it... For Webpack I have no idea.

**Comment by RachitMalik12** [comment]
Seems to work fine for me..

**Review by RachitMalik12 — APPROVED** [review]
Looks great to me! One small general comment: we need to start thinking about the stacking of all these HOC's in `/App/index.js`. That is getting messy and as we add more of these it will get worse.. 
Also, this will break #1785 because of the change of the location of the modals. Would be nice to get this merged first and then #1785. @houshuang 
Thanks!

**Review by houshuang — APPROVED** [review]

**Comment by ajainuary** [comment]
This PR causes multiple issues with the Wiki, the imports are broken without any documentation for where they are shifted to.
Edit: Resolving imports with another PR.

**Pull request merged**
