### PR TITLE
Show mouseover names for activities and operators in graph editor

### PR DESCRIPTION
**Pull request by houshuang**
This revolutionary PR displays the name of operators and activities when you put your mouse over it. Especially useful for operators, but also for activities with too long names to be displayed. We can set the delay before the tooltip is displayed in EditorContainer.

### CODE REVIEW

**Review by lfaucon — COMMENTED** [review]
The tip is not showing for operators for me.

**Comment by houshuang** [comment]
Fixed it. Turns out I had placed the component that actually shows the tooltip in a bad place, so it only worked when the sidebar was open (which also has a tooltip component :))

**Review by lfaucon — CHANGES_REQUESTED** [review]
Now it is only working for me when the sidebar is open on an activity

**Comment by houshuang** [comment]
I thought it was working before, but you're right. Fixed it again - it works for me now with or without side panel open.

**Review by lfaucon — APPROVED** [review]

**Pull request merged**
