### PR TITLE
Changelog

### PR DESCRIPTION
**Pull request by romainAA**
#1246 
The UI of the modal isn't perfect (I guess width should be fixed) but it works well.
There are also 2 dummy buttons in the logout menu for redirecting to frog website and changing password.

### CODE REVIEW

**Comment by houshuang** [comment]
Looks good, however you should keep track of the latest update seen by each user - also, they should not see any updates the first time they log in. So the first time they log in, you set the counter to the current update, and after that check if there's anything new after that.

For that you probably need version numbers in the api/versions.

**Comment by houshuang** [comment]
You should probably merge in the multipleTeacher stuff in this branch, so that we can test that it keeps track of what different users have seen etc. This functionality only makes sense with multiple teachers anyway.

**Comment by romainAA** [comment]
@houshuang Everything should be good, but since I merged MultiTeacher in it, we might want to merge multiTeacher before.

**Comment by houshuang** [comment]
@romainAA With a short changelog message, the window looks comically small - needs minimum width/height:

screen shot 2018-08-20 at 12 48 42

Other than that seems to work well. We should also add a field for date in api/changelog.js, and when we display many, we should sort them in reverse order (newest first). 

Other than that, ready to merge once we get multiTeacher in.

**Pull request merged**
