### PR TITLE
Fixing createPackage to work with new structure

### LINKED ISSUE #1226: Upgrade createPackage to work with new directory structure

### PR DESCRIPTION
**Pull request by houshuang**
Closes #1226

### CODE REVIEW

**Comment by houshuang** [comment]
@romainAA if you have time, could you help me test this so we can get it merged?

**Comment by houshuang** [comment]
@romainAA I changed how this works, can you try again? Stop Meteor before adding package, start it again afterwards, should work (problem was that it was caching the result, since you don't change any code in the activityTypes file, the babel transform wasn't rerun).

**Comment by romainAA** [comment]
Everything I checked seems to work fine, both for activities and operators

**Review by romainAA — APPROVED** [review]
Everything I checked seems to work fine, both for activities and operators

**Pull request merged**
